name: Test and publish image

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sign In
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build
        run: |
          docker build -t php72-apache -f apache.Dockerfile . \
            && docker build -t php72-fpm -f fpm.Dockerfile . \
            && docker build -t php72-composer -f fpm.Dockerfile --build-arg INSTALL_COMPOSER .

      - name: Publish images
        run: |
          docker tag php72-fpm parsilver/php-7.2
          docker tag php72-apache parsilver/php-7.2:apache
          docker tag php72-composer parsilver/php-7.2:composer
          docker push parsilver/php-7.2 \
            && docker push parsilver/php-7.2:apache \
            && docker push parsilver/php-7.2:composer
